### ISSUE TITLE
footer 的 SNS link 全錯

### ISSUE THREAD

**Issue by CrBoy** [COSCUP/coscup2017-website#19]
大概是寫的人沒資料所以沒放 link。

http://blog.coscup.org
https://www.facebook.com/coscup/
https://www.flickr.com/photos/coscup/
https://plus.google.com/+coscup
https://www.plurk.com/coscup
https://twitter.com/coscup
https://www.youtube.com/user/thecoscup

（其實 google 都找得到XD）

**Comment by Tocknicsu** [comment]
fixed
