### ISSUE TITLE
Google search 結果的標題異常

### ISSUE THREAD

**Issue by davy-tw** [COSCUP/coscup2017-website#21]
![image](https://user-images.githubusercontent.com/841969/28055063-f29d12ba-6649-11e7-9694-ff71b426c88d.png)

如圖， `/2017` 的 title 被記錄成「贊助 - COSCUP」了

**Comment by denny0223** [comment]
Fixed

![screenshot from 2017-07-13 02-27-01](https://user-images.githubusercontent.com/963044/28133538-020e59d6-6706-11e7-9f9b-1872121c5493.png)
