### ISSUE TITLE
講師照片沒吃到

### ISSUE THREAD

**Issue by TheLitchi** [COSCUP/coscup2017-website#29]
11 : 20
關於樹莓(Raspberry Pi) Bots的日常，灑種的那些日子。
Room 101 - 50 mins - ZH

14 : 15
系統管理員的奇幻之旅 - 大量部署工具進化史
Room 201 - 45 mins - ZH

有提供 link, 可連結
問題：沒有出現講師照片

**Comment by yoyo930021** [comment]
這個應該是表單沒有填好
再去追

**Comment by denny0223** [comment]
原始資料缺
